### ISSUE TITLE
Team Limitations?

### ISSUE THREAD

**Issue by KodeShinju** [Thomaz2Fast/Ultra-Hardcore-1.8#2]
I'm working with a team to host a large recorded round using this plugin however there seems to be a limit as to how many teams there can be? I was wondering if there was a way to add an increase to the team limit of 16 (or if that's just a number placed on the bukkit page). I would love to hear back soon as this round will be hosted soon. Thank you!

**Comment by KodeShinju** [comment]
<img width="178" alt="Screen Shot 2019-07-07 at 10 18 44 PM" src="https://user-images.githubusercontent.com/37993138/60778518-466d7e00-a105-11e9-8033-f9fc28c5e8fe.png">

**Comment by Thomaz2Fast** [comment]
Sorry, the limit is 16 teams, because there is only 16 different color.

But I think you can add more teams by adding them by "/team" command, but I think you can not use "select team inventory" at all.

**Comment by KodeShinju** [comment]
Other plugins I've seen will do a color with an _ (i.e. Team blue_2) and I was wondering if that was possible. It's just hard to find 16+ people at once to try and see if adding more teams is possible and going to work without being buggy. 

This is one of the only actual operating UHC plugins for this version and we would love to use it.

**Comment by KodeShinju** [comment]
So the issue is, we tried adding more teams (as well as manually assigning the person to the added team), however they don't teleport with the plugin and treats it as if they're not even in the game.

**Comment by Thomaz2Fast** [comment]
Oki, I take a look at it.

**Comment by Thomaz2Fast** [comment]
I have now update the plugin, so now you can have about 53 different teams.
Custom team names and colors.

**Comment by KodeShinju** [comment]
Teaming issue fixed and updated, thank you!
